### ISSUE TITLE
Code verify

### ISSUE THREAD

**Issue by maxsiz** [hokugava/testerc#1]
Взял Ваш код,  развернул  заново.  Отличи видите?  
Ваш   деплой  
https://rinkeby.etherscan.io/address/0x401ecae08a330a7ea6958d6579747b8cb6c75972

Мой деплой:
https://rinkeby.etherscan.io/address/0x460e72076F43A8364860126f98c7e7361C53C3Ef

Нужно научиться верфицировать код для Эзерскана.  Это де факто отраслевой стандарт

**Comment by hokugava** [comment]
Верифицировал код
